### PR TITLE
Story 6 : IFTTT RSS Feed

### PR DESCRIPTION
**Pull request by Shriyanshagro**
suggested changes as discussed in #21

### CODE REVIEW

**Comment by datakurre** [comment]
I leave this for either Kim or Sally to merge.

**Comment by Shriyanshagro** [comment]
@tkimnguyen @skleinfeldt

**Comment by skleinfeldt** [comment]
@tkimnguyen can you do it please? I have never done a merge (although I hear about them all the time, I don't do them.)

**Comment by tkimnguyen** [comment]
looking!

**Pull request merged**
