### PR TITLE
Story 13: IFTTT menu

### PR DESCRIPTION
**Pull request by Shriyanshagro**
This place IFTTT action menu on the left tab #48

### CODE REVIEW

**Comment by Shriyanshagro** [comment]
@datakurre I have followed your suggestion, however, the IFTTT actions menu doesn't pop up.
Kindly have a look at it.

**Comment by datakurre** [comment]
Thanks. I’ll look into it.

**Comment by Shriyanshagro** [comment]
@datakurre this branch is good to merge now.
I'll add related tests and update related documentation on a separate branch once #49 is also accomplished.

**Comment by datakurre** [comment]
@Shriyanshagro I reverted removal of actions so that this can be merged without issues for our test site.

**Pull request merged**
